version: '3.8'

services:
  wa-bot:
    build: .
    container_name: wa-baileys
    restart: unless-stopped
    environment:
      - TG_TOKEN=${TG_TOKEN}
      - TG_CHAT_ID=${TG_CHAT_ID}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    deploy:
      resources:
        limits:
          memory: 350M
        reservations:
          memory: 64M
    volumes:
      # Жесткая привязка ПАПКИ на сервере к ПАПКЕ в контейнере (Самый надежный метод)
      - /opt/wa_bot/data:/app/data
    stdin_open: true
    tty: true